language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t reverseproxy .
  - docker build -t udagram-api-user .
  - docker build -t udagram-api-feed .
  - docker build -t udagram-frontend .
  - docker tag reverseproxy momotimi/reverseproxy:latest
  - docker tag udagram-api-user momotimi/udagram-api-user:latest
  - docker tag udagram-api-feed momotimi/udagram-api-feed:latest
  - docker tag udagram-frontend momotimi/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push momotimi/reverseproxy-travis
  - docker push momotimi/udagram-api-user-travis
  - docker push momotimi/udagram-api-feed-travis
  - docker push momotimi/udagram-frontend-travis